### ISSUE TITLE
Update CI workflow

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#101]
Travis-ci.org was shutdown on Jun 15th, so new commits are not triggering builds (see build history [here](https://travis-ci.org/github/ocbe-uio/BayesMallows/builds)). Couple of alternatives to consider:

1. travis-ci.com (more seamless, but may require payment)
2. Github Actions (free, in-house solution, but requires completely rewriting the yml script)

**Comment by osorensen** [comment]
Thanks for notifying! I've got a colleague to set up GitHub actions set up on some other projects, and it seems to work very well.

**Comment by wleoncio** [comment]
Yeah, I've done it myself on a [different project](https://github.com/ocbe-uio/TruncExpFam/blob/develop/.github/workflows/r.yml) already; there's a learning curve there, but after the Travis burn I'd rather give Actions a try than go 3rd party again (just remembered [Jenkins](https://www.jenkins.io/) is another possibility).

**Comment by osorensen** [comment]
That's a fairly complex script! However, there is a command `usethis::use_github_action()` which sets up the defaults for the package. I'll give that a try.

**Comment by osorensen** [comment]
Even better if you know how to set this up, but I'm happy to do some work on this too :D

**Comment by wleoncio** [comment]
Leaving a post-meeting todo:

- [ ] Consider adding Solaris as a testing platform

Out of all OSs supported on CRAN, Solaris is the one with the most finicky C++ compiler, so adding it to our regular CI routine should increase robustness of the package. I would, however, wait until the GH Action script is sufficiently mature to implement this.

**Comment by wleoncio** [comment]
> That's a fairly complex script!

Yeah, the thing about GH Actions is that, unlike TravisCI, it's not a specialized CI solution but more of a generic automation tool, so even a simple CI script has to lay out all the steps of the job. On the other hand, this lower-level access should give us more power to customize our workflow. In any case, I am happy to see how fast templates for Actions are coming up, given how "new" the tool is.

**Comment by wleoncio** [comment]
From the short conversation on https://github.com/r-lib/actions/issues/249, I understand that Solaris is not a supported platform on [GitHub Actions for the R language](https://github.com/r-lib/actions) at the moment, so I think we can satisfactorily close this issue for now (and rely on R-hub for the occasional pre-submission Solaris check).

**Comment by osorensen** [comment]
Good! Although I'd love to have this automated, I would hope that running `rhub::check_with_valgrind()` occasionally will catch potential issues on Solaris.

**Comment by wleoncio** [comment]
I don't know if this works at all, but for brainstorming purposes, here's a suggestion:

1. Create a Makefile containing recipes with calls to `rhub::check(platform=c(...))` and `rhub::check_with_valgrind(platform=c(...))`, where `c(...)` contains, say, 5 of the supported platforms in `rhub::platforms()` (R-release for Linux/Mac/Win/Solaris + R-devel on Linux)
2. Have GitHub actions trigger this make recipe on some specific situations (say, a commit to `master`). This action should not happen often, since it would trigger 10 builds on R-hub (2 × 5 OSs) and 10 e-mails to the maintainer.
