### ISSUE TITLE
Make unit tests run faster

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#102]
Many of the tests both in the master branch and in smc-mallows take too long to run. It is necessary to go through all tests and check if the number of iterations can be reduced.

**Comment by wleoncio** [comment]
PR #103 fixes unit tests on the master branch, so this issue remains open until the smc tests are also simplified.

**Comment by wleoncio** [comment]
Added this issue to the SMC-Mallows project, since all remaining tests to be optimized are related to it.

**Comment by wleoncio** [comment]
SMC tests have been optimized (see b0c482c7b31e6a5e9ff27b1e63b5523e687f982c for details), reducing SMC-test length from 19.8 s to 5.7 s (delta = -14.1 s). The longest tests in the package are under the "SMC new users partial rankings" context (5.3 s), but I believe we can go < 1 s there once the functions are translated to C++ (i.e., once issues #98 and #107 are closed). In particular, `metropolis_hastings_aug_ranking()` is responsible for 2/3 of that runtime according to `Rprof()`.

**Comment by osorensen** [comment]
Great work!
