### ISSUE TITLE
Unexpected output?

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#116]
Hi @anjastein,

I have a question regarding this bit of test code:

https://github.com/ocbe-uio/BayesMallows/blob/d1e075dbad16cfa71997992485a42eb5dfd6b785/tests/testthat/test_smc_pseudolikelihood.R#L23-L63

In the original, `test_1_forward$aug_ranking` was `1 2 3 5 4 6`. This changed to `1 2 3 6 5 4` after the function was translated into C++, which I understand is fine. I am worried about the consequences, though.

Specifically, this different `test_1_forward$aug_ranking` becomes the `current_ranking` for `test_1_backward_b`, which consequently outputs a different probability (0.03699547 against 0.07205734 from the original code). I guess that is OK as well.

My problem is with the final bit of this test, `test_1_forward$forward_prob == test_1_backward_b`. This used to be true in the original implementation, but now it's false because the left side still equals 0.07205734 and the right side changed to 0.03699547 after the translation. I checked the original R code for bwd_prob and the results seem correct (i.e., the probability changes because the current rankings change, indicating the translated function outputs like original), but I wonder if there is some methodological expectation I am missing here.

**Comment by anjastein** [comment]
Apologies, just seen this! I shall give this try and run this script on my desktop as well as update email notificiation permissions.

**Comment by anjastein** [comment]
Just tested it and I now get these results
![image](https://user-images.githubusercontent.com/45001848/140318570-999b12eb-02af-4163-82be-a08887d83ad4.png)

**Comment by anjastein** [comment]
I suspect that there may be a bug, but I assume that the unit tests for `calculate_forward_probability` and `calcaulate_backward_probability` are passing...

**Comment by wleoncio** [comment]
Yeah, all but three tests pass. These are the failure reports (curated output from `devtools::test(filter = "pseudolik")`):

```R
Failure (test_smc_pseudolikelihood.R:62:3): calculations of forward and backward probabilities
test_1_forward$aug_ranking not equal to matrix(c(1, 2, 3, 6, 5, 4)).
3/6 mismatches (average diff: 1.33)
[4] 4 - 6 == -2
[5] 6 - 5 ==  1
[6] 5 - 4 ==  1

Failure (test_smc_pseudolikelihood.R:63:3): calculations of forward and backward probabilities
test_1_forward$forward_prob not equal to 0.07205734.
1/1 mismatches
[1] 0.037 - 0.0721 == -0.0351

Failure (test_smc_pseudolikelihood.R:65:3): calculations of forward and backward probabilities
`test_1_backward_b` not equal to test_1_forward$forward_prob.
1/1 mismatches
[1] 0.0817 - 0.037 == 0.0447
```

So the first one refers to a mismatch in the aug_ranking output (ranks 4, 5, and 6 are switched, no biggie) and the other two are the differences in probability. Nothing new, there. I'll take a further look into this. 🤕

**Comment by wleoncio** [comment]
Ok, I've just pushed version 1.0.3.9007 to the `issue-116-unexpected-output` branch, which can be installed with

```r
remotes::install_github("ocbe-uio/BayesMallows", "issue-116-unexpected-output")
```

After that, running `devtools::test(filter = "pseudolik")` (better yet, running the script on `tests/testthat/test_smc_pseudolikelihood.R` line by line) will eventually lead to this:

```r
r$> test_1_forward <- calculate_forward_probability( 
      item_ordering = item_ordering, partial_ranking = partial_ranking, 
      remaining_set = remaining_set, rho = rho, alpha = alpha, 
      n_items = n_items, metric = metric 
    ) # TODO #116: get this to output aug_ranking == c(1, 2, 3, 6, 5, 4).                                                                                                                                                                                          
0 fwd = 1
1 fwd = 0.384937
2 fwd = 0.0886268

r$> # Tried all combinations of item_ordering. No dice. 
     
    current_ranking <- c(1, 2, 6, 5, 4, 3)                                                                                                                                                                                                                         

r$> test_1_backward_a <- calculate_backward_probability( 
      item_ordering = item_ordering, partial_ranking = partial_ranking, 
      current_ranking = current_ranking, remaining_set = remaining_set, rho = rho, 
      alpha = alpha, n_items = n_items, metric = metric 
    )                                                                                                                                                                                                                                                              
0 bck = 1
1 bck = 0.14161
2 bck = 0.032604

r$> new_current_ranking <- test_1_forward$aug_ranking # c(1, 2, 3, 4, 6, 5)                                                                                                                                                                                        

r$> # new_current_ranking needs to be one of the following so that test_1_backward_b 
    # equals test_1_forward$forward_prob: 
    # - c(1, 2, 3, 6, 5, 4) 
    # - c(1, 2, 6, 4, 3, 5) 
    test_1_backward_b <- calculate_backward_probability( 
      item_ordering = item_ordering, partial_ranking = partial_ranking, 
      current_ranking = new_current_ranking, remaining_set = remaining_set, rho = rho, 
      alpha = alpha, n_items = n_items, metric = metric 
    )                                                                                                                                                                                                                                                              
0 bck = 1
1 bck = 0.384937
2 bck = 0.123689
```

So the fwd and bck probabilities start diverging on step 2 (the output for `test_1_backward_a` doesn't matter IIRC). Will investigate further ASAP.

**Comment by anjastein** [comment]
I've copied your print statements into the original R code for these functions. I get the following output:
![image](https://user-images.githubusercontent.com/45001848/140570294-5609aebd-5f0e-41b3-8795-a35a032fdcbd.png)
![image](https://user-images.githubusercontent.com/45001848/140570346-9a3e9d7a-19c5-4075-b1cc-04981e6ea090.png)

It looks like something might be causing different probabilities to be calculated in the function `calculate_backwards_probability` so I'll keep digging into the code

**Comment by wleoncio** [comment]
Hey @anjastein, any leads so far on this issue?

FYI, I've just pushed branch `issue-116-unexpected-output` again (I've accidentally deleted the remote branch some time in the past and only realized it now). This is a new build version, 9008, which incorporates the many recent changes in the codebase. The issue described in the OP here still persists, though.

**Comment by anjastein** [comment]
Hi!
Not yet, I'm afraid. I've had an unsuccessful coding week, but I'll try again this week!

**Comment by anjastein** [comment]
Hi,

Good news! I suspect that the function `calculate_forward_probability.cpp`  is missing a final line of code before returning its output list, so we may have found an explanation/solution for the bug.

After it has iteratively selected the ranks for each item in the vector `item_ordering`, it should then create the auxiliary ranking by ordering the ranks in `partial_ranking` in order of the vector `item_ordering`. 

In the example, both scripts have the `item_ordering = c(3,6,4,5)` and `partial_ranking = c(1,2,NA,NA,NA,NA)`.

In the R version of `calculate_forward_probability`, the items in `item_ordering`  (`c(3,6,4,5)`) are assigned ranks 3,4,6,5 respectively.
Then, they are reordered correctly to give the augmented ranking
 `partial_ranking[item_ordering] <- auxiliary_ranking`, which gives the result `aug_ranking = c(1,2,3,6,5,4)`.

In the C++ version, we have had to change `set.seed(101)` (In R, `set.seed(104)`) to see what is going on. 
We get the output `aug_ranking = c(1,2,3,6,4,5)`, but that is because in this run of `calculate_forward_probability.cpp` we have assigned the items in  `item_ordering = c(3,6,4,5)`) to be assigned the ranks 3,6,4,5, which happens to the same order as the augmented component of `aug_ranking`. But these values do not get rearranged by item ordering when we create the vector `aug_ranking` - they just replace the NA values with the assigned ranks 3,6,4,5,.
I think the `aug_ranking` for this value of `set.seed` should be `c(1,2,3,6,4,5)` instead of `c(1,2,3,6,5,4)`. 

So I think we need to add a line of code to `calculate_forward_probability.cpp` that does something like
` partial_ranking[item_ordering] <- auxiliary_ranking;`
`aug_ranking = partial_ranking;`

**Comment by anjastein** [comment]
The is my console print out with the R version:
![image](https://user-images.githubusercontent.com/45001848/142444590-29f42fbb-aa9e-4609-9a71-e63acf5507c3.png)
![image](https://user-images.githubusercontent.com/45001848/142444669-62d6e26f-1965-4f24-81f0-8fc8a880a378.png)

This is the console printout with the C++ version:
![image](https://user-images.githubusercontent.com/45001848/142445073-799a99f3-5fd7-4fb7-a2f1-f211ccadae2b.png)
![image](https://user-images.githubusercontent.com/45001848/142445171-4e8aab08-4ca1-4ad2-97cb-557d5a08a053.png)
![image](https://user-images.githubusercontent.com/45001848/142445261-b3cfe0de-7161-49b9-b67f-c90e21db2b5b.png)
![image](https://user-images.githubusercontent.com/45001848/142445316-93a86776-7555-49d9-90d1-e40b6658b04b.png)

I think if we use the same seed value after implementing the changes to the code, then hopefully we will get the same output in the unit tests!

**Comment by anjastein** [comment]
I wish I had a more sophisticated approach when I was debugging, but hindsight is 20/20!

**Comment by wleoncio** [comment]
Good job, Anja! Lemme see if I can get this done before our next meeting. 🤞🏽

**Comment by wleoncio** [comment]
Bug was introduced on commit ce5d52cd006eddacc489a344f07e651835ed349e, when I started working around another issue related to `calculate_forward_probability()` having to handle both R and C++-style indices.

Issue is fixed on commit e5027baa (to be merged soon). So happy to see this sorted out! :happy:

**Comment by wleoncio** [comment]
Still a bit of work to do before triggering the great merge (issue-116 -> smc-mallows -> develop). PRs #154 and #156 removed the tidyr dependency, but this branch still contains two calls to `gather()` and one to `spread()` that should be replaced ASAP. I'm checking @osorensen's work on the aforementioned PRs for inspiration on how to do that.

**Comment by osorensen** [comment]
Reach out if I can be of any help. Beware that `stats::reshape` doesn't like tibbles, so an `as.data.frame` is often needed. We'll deal with the tibbles later, when removing dplyr.

**Comment by wleoncio** [comment]
tidyr problems solved (commits 04546087 and c62c9195), but the vignette needs a bit of rework since it started to fail. I'll get back to it on Monday morning.

**Comment by osorensen** [comment]
Well done @wleoncio!

**Comment by wleoncio** [comment]
All done!
