### ISSUE TITLE
Unable to perform MCMC steps with one ranking (get_mallows_loglik.cpp)

### ISSUE THREAD

**Issue by anjastein** [ocbe-uio/BayesMallows#134]
Hi, 
I've noticed that I am unable to perform a Metropolis-Hastings step to update the value of rho or alpha if I happen to have one ranking only. I've attached an example script and the error that I am receiving.

![image](https://user-images.githubusercontent.com/45001848/139647952-3dc8afcb-0bf1-43a6-8996-acd36be43df3.png)

I suspect that it may be to do with the variable types for `rankings` because we already have a test-that script for the function `get_mallows_loglik` to check that the function works with one ranking.

**Comment by wleoncio** [comment]
Hi @anjastein,

Does it work if you pass `rho_init` as `as.matrix(rho_init)`?

**Comment by wleoncio** [comment]
If that doesn't work, please share your script as a text file (for example, by uploading it to https://gist.github.com/ and sharing the link).

**Comment by wleoncio** [comment]
To be a bit more precise about what I'm trying to achieve: The input to `metropolis_hastings_alpha()` must follow this class list:

```cpp
arma::vec metropolis_hastings_rho(
	double alpha,
	int n_items,
	arma::mat rankings,
	std::string metric,
	arma::vec rho,
	int leap_size
) 
```
So for example `rankings` must be a matrix, and it looks like `cluster_rankings <- sushi_rankings[1, ]` isn't, so I'd also try passing it with `as.matrix(cluster_rankings)`.

**Comment by anjastein** [comment]
Following your suggestions, I now get a new error message from the function `get_rank_distance`,
Error: r1 and r2 must have the same length,
even though `length(as.matrix(rho_init)) == length(as.matrix(cluster_rankings))` evaluates the statement as `TRUE`.

I have also tried a different combinations of setting `rho_init` and `cluster_rankings` as `as.matrix()` or not and I still get these error messages.

**Comment by anjastein** [comment]
Here's the gist link:
https://gist.github.com/anjastein/7d85d6d5b0135869ad3fb15d60f8b38b

**Comment by wleoncio** [comment]
So the following seems to work here:

```r
metropolis_hastings_rho(
    alpha = alpha_init, n_items = n_items, rankings = t(as.matrix(cluster_rankings)), 
    metric = metric, rho = rho_init, leap_size = leap_size
)
```

Can you confirm this solves the issue on your end?

The trick is to have both `rho` and `rankings` as row vectors. I think I could add a bit of code to `get_mallows_loglik()` to verify these dimensions and make sure they match before calling `get_rank_distance()` (which is where the "r1 and r2" length error comes from.

**Comment by anjastein** [comment]
Yes, it does, thank you! I shall transpose these vectors in future and make a conditional statement in my experimental scripts.

**Comment by wleoncio** [comment]
Great! I'll work on making those functions a bit "smarter". In the meantime, just remembered that `t(cluster_rankings)` also works (`t()` already converts an R sequence to a matrix, so the `as.matrix()` part is redundant).
