### ISSUE TITLE
More useful error message when theta is missing

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#144]
Running assess_convergence with parameter="theta" when `error_model=NULL` results in a not very informative error message.

``` r
library(BayesMallows)
m <- compute_mallows(potato_visual)
assess_convergence(m, parameter = "theta")
#> Error: `data` must be a data frame, or other object coercible by `fortify()`, not a numeric vector.
```

<sup>Created on 2021-11-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We do however have an error message in the function being called by assess_convergence, but this error message is not invoked, because `is.null(m$theta)` is `FALSE`.

https://github.com/ocbe-uio/BayesMallows/blob/3c78d811f762a6076f1f833137d3a5541229755a/R/assess_convergence.R#L187-L198

**Comment by wleoncio** [comment]
Resolved by b096ec3.
