### ISSUE TITLE
SMC Mallows should be able to utilize exact partition functions

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#158]
@wleoncio and @anjastein, I'm working through the pull request now, and notice the following lines in the vignette:

https://github.com/ocbe-uio/BayesMallows/blob/b36d362ce3a6184d041d6605b7171bb4c084296d/vignettes/SMC-Mallows.Rmd#L120-L144

Using importance sampling here seems unnecessary, because we have the exact partition function for 10 items with the footrule stored in the package. With `compute_mallows`, we would simply run the following lines, using the default argument `logz_estimate = NULL`. 

```r
metric <- "footrule"
data <- sushi_rankings[1:100,]
bm_test <-  compute_mallows(rankings = data)
```

How this works can be seen in the following line in `compute_mallows`:

https://github.com/ocbe-uio/BayesMallows/blob/bee19d40130ed4745a071b4657753c3e10a4695e/R/compute_mallows.R#L353

Which then calls this internal function, that uses the internal dataframe `BayesMallows::partition_function_data`.

https://github.com/ocbe-uio/BayesMallows/blob/bee19d40130ed4745a071b4657753c3e10a4695e/R/misc.R#L36-L72

As far as I can tell, fixing this issue requires us to create R wrappers around the `smc_*` function, so that we are able to preprocess the user input before calling C++. We don't need this for the first release, but it is important to eventually fix this, as importance sampling both takes some time and is less accurate than the exact partition functions.

We also have some precomputed importance sampling estimates in there, as shown by the following

```r
> table(BayesMallows:::partition_function_data$type)

#>      cardinalities importance_sampling 
#>                159                  15 
```

**Comment by wleoncio** [comment]
That's good to know, because `estimate_partition_function()` does take a while indeed. How many items are covered by `partition_function_data`, exactly? 10? Up to and including 10? 10 or more?

**Comment by osorensen** [comment]
The exact partition functions are based on the [On-Line Encyclopedia of Integer Sequences](https://oeis.org/), which is called `cardinalities`in `BayesMallows:::partition_function_data`. In addition, we precomputed some importance sampling estimates for the Spearman distance since the exact integer sequences were only available up to 14 items.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
BayesMallows:::partition_function_data %>% 
  group_by(metric, type) %>% 
  summarise(
    max_items = max(n_items),
    .groups = "drop"
  )
#> # A tibble: 4 × 3
#>   metric   type                max_items
#>   <chr>    <chr>                   <int>
#> 1 footrule cardinalities              50
#> 2 spearman cardinalities              14
#> 3 spearman importance_sampling        29
#> 4 ulam     cardinalities              95
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


I realize that this is a bit hidden, and that it would probably be useful to write a vignette or some other documentation on it.

**Comment by wleoncio** [comment]
I'd like to get some help understanding a bit of the methodology before trying to propose a solution.

On the script below, is the idea to use `logz_estimate_2` instead of `logz_estimate`? I see both successfully output SMCMallows objects with the same structure and nearly-identical values except for the different `ESS` vectors. Is this a problem? Having `logz_estimate*` objects with very different sizes and values doesn't sound right, but I may be wrong.

``` r
# Setting common parameters
library(BayesMallows)
print(packageVersion("BayesMallows")) # For reproducibility
#> [1] '1.2.2'
data <- sushi_rankings[1:100, ]
n_items <- ncol(data)
metric <- "footrule"

# Calculating logz_estimate
logz_estimate <- BayesMallows::estimate_partition_function(
  "importance_sampling", seq(0, 15, 0.1), n_items, metric, 1e3, 10
)

# Alternative calculation of logz_estimate
logz_list <- BayesMallows:::prepare_partition_function(NULL, metric, n_items)
logz_estimate_2 <- logz_list$cardinalities

# Showing that the estimates are not the same in value and size
print(logz_estimate)
#>   (Intercept)    I(alpha^1)    I(alpha^2)    I(alpha^3)    I(alpha^4) 
#>  1.511372e+01 -3.407066e+00  4.673231e-01 -1.677822e-01  7.476009e-02 
#>    I(alpha^5)    I(alpha^6)    I(alpha^7)    I(alpha^8)    I(alpha^9) 
#> -2.004337e-02  3.219276e-03 -3.166730e-04  1.871405e-05 -6.101159e-07 
#>   I(alpha^10) 
#>  8.433447e-09
print(logz_estimate_2)
#>  [1]      1      9     52    224    790   2350   6072  13768  27821  50461
#> [11]  83420 127840 182256 242272 301648 350864 382576 389232 373536 332640
#> [21] 273060 208548 136512  81792  46656  14400

# Running SMC routine
leap_size <- floor(n_items / 5)
N <- 1000
Time <- 20
seed <- 630072L
set.seed(seed)
smc_test <- smc_mallows_new_users(
  data, "complete", n_items, N, Time, 5, 5, metric = metric,
  leap_size = leap_size, logz_estimate = logz_estimate
)
set.seed(seed)
smc_test_2 <- smc_mallows_new_users(
  data, "complete", n_items, N, Time, 5, 5, metric = metric,
  leap_size = leap_size, logz_estimate = logz_estimate_2
)

# Printing outputs for comparizon
print(str(smc_test))
#> List of 4
#>  $ rho_samples       : num [1:1000, 1:10, 1:21] 9 10 4 1 2 5 2 5 9 2 ...
#>  $ alpha_samples     : num [1:1000, 1:21] 1.267 2.553 0.213 2.262 0.476 ...
#>  $ augmented_rankings: num[0 , 0 , 0 ] 
#>  $ ESS               : num [1, 1:20] 114.2 343.4 203.7 11.3 406.7 ...
#>  - attr(*, "class")= chr "SMCMallows"
#> NULL
print(str(smc_test_2))
#> List of 4
#>  $ rho_samples       : num [1:1000, 1:10, 1:21] 9 10 4 1 2 5 2 5 9 2 ...
#>  $ alpha_samples     : num [1:1000, 1:21] 1.267 2.553 0.213 2.262 0.476 ...
#>  $ augmented_rankings: num[0 , 0 , 0 ] 
#>  $ ESS               : num [1, 1:20] 30.9 835.2 907.8 945 964.9 ...
#>  - attr(*, "class")= chr "SMCMallows"
#> NULL
print(all.equal(smc_test, smc_test_2))
#> [1] "Component \"rho_samples\": Mean relative difference: 0.6488713"  
#> [2] "Component \"alpha_samples\": Mean relative difference: 0.9985283"
#> [3] "Component \"ESS\": Mean relative difference: 2.0659"
print(summary(as.vector(smc_test$ESS)))
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   11.31  191.59  231.32  305.31  419.15  684.48
print(summary(as.vector(smc_test_2$ESS)))
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   30.93  972.22  990.30  927.72  995.52  997.72
```

<sup>Created on 2023-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Looking at the code for `smc_mallows_new_users()`, the `ESS` vector is modified by [this subroutine](https://github.com/ocbe-uio/BayesMallows/blob/develop/src/smc_mallows_new_users_funs.cpp#L142), so maybe the differences are ultimately caused by different values of [`log_z_alpha`](https://github.com/ocbe-uio/BayesMallows/blob/develop/src/smc_mallows_new_users_funs.cpp#L127-L129) (I'm supposing the common "partition" theme here is related to the issue)?

FWIW, print-debugging showed me that `logz_estimate` was generating `log_z_alpha` around 10, whereas the `_2` variation had values around 1.

**Comment by osorensen** [comment]
Nice that you're looking at this.

To your first question: The idea is that `logz_estimate` and `logz_estimate2` should give the same values, but they should be treated differently. `logz_estimate` contains coefficients for a polynomial approximation to the partition function where `logz_estimate2` is numbers that can be used in a special sum in sum special cases. `logz_estimate2` are the exact partition functions, and we have these available for some combinations of distance measures and numbers of items in `BayesMallows:::partition_function_data`.

I'll illustrate what happens in the standard MCMC case. If you call `compute_mallows`, you eventually get to this line:

https://github.com/ocbe-uio/BayesMallows/blob/238e400a5a01eaa2791d6c2e9be803efba55033d/R/compute_mallows.R#L348

which again leads to this function

https://github.com/ocbe-uio/BayesMallows/blob/238e400a5a01eaa2791d6c2e9be803efba55033d/R/misc.R#L32-L67

If the user has provided a `logz_estimate` to `compute_mallows`, then it returns from the first if statement. Otherwise we proceeed, and check if we either have an integer sequence (corresponding to `logz_estimate2`) or a precomputed importance sampling estimate. Based on this, we return back to `compute_mallows`.

Back in `compute_mallows`, there are now two arguments provided to the C++ function `run_mcmc`, and they may be `NULL`:

https://github.com/ocbe-uio/BayesMallows/blob/238e400a5a01eaa2791d6c2e9be803efba55033d/R/compute_mallows.R#L367-L368

From `run_mcmc`, these arguments are used by `update_alpha` (and by clustering functions) as here. Actually, they are just forwarded to `get_partition_function`:

https://github.com/ocbe-uio/BayesMallows/blob/238e400a5a01eaa2791d6c2e9be803efba55033d/src/parameterupdates.cpp#L23-L66

Here is `get_partition_function`, which selects how to compute the partition function based on what we give to it:

https://github.com/ocbe-uio/BayesMallows/blob/238e400a5a01eaa2791d6c2e9be803efba55033d/src/partitionfuns.cpp#L112-L123

- `exact_logz` is for the cases where we can easily compute the partition function exactly.
- `compute_is_fit` compute the prediction from the polynomial approximation at the particular `alpha` being asked for.
- `logz_cardinalities` takes the numbers in the vector (corresponding to your `logz_estimate2` above) and finds the exact partition based on these.

So it would be nice if SMC Mallows could utilize these functions for selecting the partition function, rather than requiring that the user provides it.

**Comment by wleoncio** [comment]
Thank you for the detailed explanation, Øystein! I'll study the issue further, hope it doesn't take too long until I can come up with a solution. 😅

**Comment by osorensen** [comment]
Reading through this >4 years after implementing it the first time, I realize the design is pretty terrible. This would be the perfect case for defining a class rather than having lots of code to deal with the different cases. So feel free to explore possibly new solutions here :-)

**Comment by osorensen** [comment]
@wleoncio, I'm going to take a look at this issue now, just letting you know.

**Comment by osorensen** [comment]
Close by #304
