### ISSUE TITLE
plot_alpha_posterior gives warning

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#159]
`plot_alpha_posterior` in #157 gives a warning, as can be seen by this reprex.

``` r
library(BayesMallows)
n_items <- dim(sushi_rankings)[2]
metric <- "footrule"
alpha_vector <- seq(from = 0, to = 15, by = 0.1)
iter <- 1e4
degree <- 10
# Estimate the logarithm of the partition function of the Mallows rank model
logz_estimate <- estimate_partition_function(
  method = "importance_sampling",
  alpha_vector = alpha_vector,
  n_items = n_items, metric = metric,
  nmc = iter, degree = degree
)
data <- sushi_rankings[1:100, ]
leap_size <- floor(n_items / 5)
N <- 1000
Time <- 20
smc_test <- smc_mallows_new_users_complete(
  R_obs = data, n_items = n_items,
  metric = metric, leap_size = leap_size,
  N = N, Time = Time,
  logz_estimate = logz_estimate,
  mcmc_kernel_app = 5,
  num_new_obs = 5,
  alpha_prop_sd = 0.5,
  lambda = 0.15,
  alpha_max = 1e6
)


test_sample_alpha <- smc_test$alpha_samples[, Time + 1]
plot_alpha_posterior(
  output = test_sample_alpha, nmc = N,
  burnin = 0
)
#> Warning: Use of `alpha_samples_table$value` is discouraged. Use `value` instead.
```

![](https://i.imgur.com/bE7vVJ8.png)

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is not being caught be the automated tests because there is no test for the function. I will fix this in a commit, and create a test which will catch this later.

**Comment by wleoncio** [comment]
Good catch, I tend to ignore tests on plot functions unless they are capable of giving out some textual, testable output (e.g. through a `plot = FALSE` kind of parameter), but that does mean leaving such warnings undetected. This should be investigated and addressed before release, I think.

**Comment by wleoncio** [comment]
BTW, I hope I remember to ask you to demo that reprex package to me in our next meeting, looks useful to automate reports! 😄

**Comment by osorensen** [comment]
Yes, reprex is very useful. All you need to make sure the script you want to run is on the clipboard, and then type `reprex::reprex()` in the R console.

**Comment by wleoncio** [comment]
That was quick, dude's on fire 😆
