### ISSUE TITLE
Outputs with different classes on compute_rho_consensus

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#163]
I have attached a gist with the proposed unit test. I've noticed that the function does not return a tibble table when `type="MAP", so the function may need a minor change if necessary
https://gist.github.com/anjastein/c05eb5ce5fae290671e92e62565125d7

_Originally posted by @anjastein in https://github.com/ocbe-uio/BayesMallows/issues/80#issuecomment-983623423_

# Tasks

- [ ] 
- [x] Fix output on MAP
- [x] Add unit test to package

**Comment by wleoncio** [comment]
I'm not sure what lies in the future regarding output formats for the package (we should eventually talk about whether handling issue #162 means package outputs should be data frames instead of tibbles), but as of the current state, I agree that it looks off to have two similar functions output different classes.

**Comment by osorensen** [comment]
I agree with you @wleoncio, that when #162 is resolved, all the output should be `data.frames`, but let's deal with that later. `dplyr::as_tibble()` might fix this issue for now?

**Comment by wleoncio** [comment]
I didn't have time to look at the code, but that sounds like the best solution: one small transformation just before the return statement that can be easily dropped in the future.
