### ISSUE TITLE
Replace 1:length(x) on compute_mallows()

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#168]
As pointed out on PR #167, L330 of the compute_mallows() function contains a piece of code that could be improved. Some alternatives:

1. Replace `1:length(x)` with `seq_along(x)` (or whatever is most appropriate)
2. Add that particular line to the `exclusions` argument of the linter YAML script
3. Drop the `seq_linter` from the linter YAML script

Whatever the case, the package would benefit from some tests covering that line of code, perhaps testing for different lengths of `x` (including 0).

**Comment by osorensen** [comment]
Isn't alternative 1 definitely best?

**Comment by wleoncio** [comment]
Definitely, I just wasn't comfortable enough with that function to make the change without fear of any side-effects 😆  Thanks for fixing!

**Comment by osorensen** [comment]
That was definitely the right choice, and now we have a unit test covering those lines :-)
