### ISSUE TITLE
New CRAN issue

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#181]
I resubmitted to CRAN after fixing #178, and got this one back:

> Flavor: r-devel-linux-x86_64-debian-gcc
Check: R code for possible problems, Result: NOTE
 Found if() conditions comparing class() to string:
 File 'BayesMallows/R/plot_elbow.R': if (length(models) == 1 && !(class(models[[1]]) == "BayesMallows")) ...
 Use inherits() (or maybe is()) instead.
>
> Please fix and resubmit.

I'll look at it.

**Comment by wleoncio** [comment]
Yeah, they are not big fans of `if(class(...))` anymore 😛 

Perhaps switching to `is(class(...), ...)` on the following statements will fix the issue without any negative side effects:

https://github.com/ocbe-uio/BayesMallows/blob/7ddd63a64ae2d54296f634af890ca86f98c30668/R/generate_initial_ranking.R#L75

https://github.com/ocbe-uio/BayesMallows/blob/7ddd63a64ae2d54296f634af890ca86f98c30668/R/plot_elbow.R#L32

P.S.: the `develop` branch got (accidentally?) deleted on #180.

**Comment by osorensen** [comment]
Thanks, I noticed the one in `plot_elbow.R`, but not the one in `generate_initial_ranking.R`, so will change that one as well. 

PS! Indeed, I'll create another develop branch :-)
