### ISSUE TITLE
Add CRAN flags to GH Actions

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#194]
See https://github.com/ocbe-uio/BayesMallows/pull/188#issue-1197698274 for more information.

The basic idea, though, is to try to add the C++ flags below to our CI workflow so it simulates the CRAN checks more closely, at least when pushing to master:

```
Compilation logs for CRAN packages using x86_64 Fedora 34 Linux 
built with configure --enable-lto=R and config.site:

CFLAGS="-g -O2 -Wall -pedantic -mtune=native"
FFLAGS="-g -O2 -mtune=native -Wall -pedantic"
CXXFLAGS="-g -O2 -Wall -pedantic -mtune=native -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-parentheses"
AR=gcc-ar
RANLIB=gcc-ranlib
LTO=-flto=10
LTO_OPT=-flto

and packages under test installed with INSTALL --use-LTO.


Look for [-Wlto-type-mismatch] warnings.  In some cases these involve
Fortran CHARACTER arguments where the length is passed as a 'hidden'
argument at the end, giving mismatches such as

sblas.f:3951:14: note: type ‘long int’ should match type ‘void’

To work around these, define USE_FC_LEN_T and include Rconfig.h
(perhaps via R.h) before including BLAS.h or Lapack.h or your own
C proptypes for Fortran functions.  Then amend the actual calls to include
character length arguments: see the example of src/library/stats/src/rWishart.c
in the R sources.
```

**Comment by osorensen** [comment]
I think rhub on Docker has many of the things we need: https://hub.docker.com/u/rhub. In particular rhub/debian-gcc-devel-lto

Here is a blog post describing how to use GitHub Actions with Docker images.

I might give it a try during the holidays.

**Comment by wleoncio** [comment]
I wonder if this is still worthy to pursue.

The [v2 r-lib/action check-release.yaml](https://github.com/r-lib/actions/blob/v2-branch/examples/check-release.yaml) template has greatly reduced the need for customized code, though it's hard to say whether it included improvements related to compiled code. In any case, the C++ issues related in the OP haven't reappeared in almost one year with 3 package releases. Moreover, the most recent C++ check issue (see #279) was hard to predict and hardcode in a config file, so I'm afraid any attempts to do so would simply be ineffective.

@osorensen, did you get anywhere interesting with that Actions + Docker idea above? If not, maybe we should just close this, mark it as "wontfix", and perhaps come back to it if we change our minds.

**Comment by osorensen** [comment]
Agree!
