### ISSUE TITLE
using namespace arma?

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#197]
If I remember correctly, you've suggested this before @wleoncio, but do you agree that we could add `using namespace arma` to the `cpp` source files to avoid using the `arma::` qualifier everywhere?

**Comment by wleoncio** [comment]
I think it's a good idea, it would make the code more readable. This might be best done slowly, though, to facilitate conflict-handling. Here's a suggestion for commits, roughly ordered by breakage potential:

- [ ] Drop `arma::` from Arma classes (sword, iword, uword, vec, ivec, rowvec, mat, cube...)
- [ ] Drop `arma::` from Arma-generated objects(ones, zeros, rand*...)
- [ ] Drop `arma::` from Arma functions (conv_to, find, find_nonfinite, sum, cumsum, join_cols, min, max, norm, normalise, repmat, shuffle, sort, unique)
