### ISSUE TITLE
new version for how smc_mallows_new_item_rank_* is initialised

### ISSUE THREAD

**Issue by anjastein** [ocbe-uio/BayesMallows#198]
Hi both, 

The functions with names beginning with `smc_mallows_new_item_rank_*` would benefit from using output from `smc_mallows_new_users_*` to be the initial sample of `rho` and `alpha` in the system. I have the proposed code written in R which could benefit from being translated into C++. @wleoncio, would you be interested in this? The code still suffers from DRY issues, but it does mean the translation should not be time-consuming.... What do you think?

**Comment by wleoncio** [comment]
Sounds interesting, show me the code! :)

**Comment by wleoncio** [comment]
Hi @anjastein, just started getting back to this now that 1.2.0 is out and the API has settled a bit.

Quick question. The code you sent me back in April mentions two functions, `smc_mallows_new_users_uniform()` and `smc_mallows_new_users_pseudo()`, to be adapted to whatever the new API ended up being. So I am changing the updated new rank functions assuming these two functions respectively correspond to `smc_mallows_new_users(type = "partial", aug_method = "random")` and `smc_mallows_new_users(type = "partial", aug_method = "pseudolikelihood")`, is that so?

**Comment by anjastein** [comment]
Yes, that sounds about right! :)
