### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#209]
The documentation is not up-to-date for smc_mallows_new_users_complete:

https://github.com/ocbe-uio/BayesMallows/blob/4c8c4fc15c88ab78ffacc2beada6126919016a5d/src/smc_mallows_new_users_complete.cpp#L43

But the return value is

https://github.com/ocbe-uio/BayesMallows/blob/4c8c4fc15c88ab78ffacc2beada6126919016a5d/src/smc_mallows_new_users_complete.cpp#L199-L203

See also comment on #193.

**Comment by wleoncio** [comment]
Required to close #190, #191, #192 and #193.

**Comment by osorensen** [comment]
Closed by #193
