### ISSUE TITLE
Remove dplyr dependencies in examples and tests

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#212]
#211 moves dplyr from Imports to Suggests, which is a great improvement in terms of the package's dependencies. However, dplyr is still present in lots of examples and tests.

**Comment by wleoncio** [comment]
Also present on the SMC-Mallows vignette:

https://github.com/ocbe-uio/BayesMallows/blob/30367ebddbac0509a8e40920eefdd7bd6051f784/vignettes/SMC-Mallows.Rmd#L29

Technically, a few meta-package scripts for data generation also contain calls to dplyr. Not necessary to change, but if one's on a roll... 😄 
1. https://github.com/ocbe-uio/BayesMallows/blob/30367ebddbac0509a8e40920eefdd7bd6051f784/data-raw/generate_beach_data.R
2. https://github.com/ocbe-uio/BayesMallows/blob/30367ebddbac0509a8e40920eefdd7bd6051f784/data-raw/generate_internal_data.R
3. https://github.com/ocbe-uio/BayesMallows/blob/30367ebddbac0509a8e40920eefdd7bd6051f784/data-raw/importance_sampling/estimate_z.R

**Comment by osorensen** [comment]
On a personal notice, replacing dplyr is the perfect activity inbetween diaper change, so might be able to put down some work towards this one 👨‍🍼 👶

**Comment by osorensen** [comment]
Closed by #216
