### ISSUE TITLE
Simplifying SMC-Mallows interface

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#233]
@wleoncio and @anjastein, what do you think about this idea for simplifying the interface to the `smc_mallows_new_users_*`?

Rather than having `smc_mallows_new_users_partial()`, `smc_mallows_new_users_partial_alpha_fixed()`, and `smc_mallows_new_users_complete()`, we could have a single `smc_mallows_new_users()`, which took all the arguments needed, plus an additional argument specifying the type (e.g., `type = "partial_alpha_fixed"`, `type = "partial"`, `type = "complete"`). 

The following come to mind for me, but I'd love to hear your thoughts.

## Pros
- Easier to maintain and document, since we keep it all in the same place.
- The users can look at the documentation of a single function, rather than three.

## Cons
- The different options yields different return values. For example, `"complete"` does not have `aug_rankings` whereas `"partial_alpha_fixed"` does not have `alpha_samples`. We could fix this by setting the corresponding list element to `NULL`.

**Comment by wleoncio** [comment]
I'm on board, and judging by @anjastein's thumbsup on a similar commento of mine (https://github.com/ocbe-uio/BayesMallows/issues/114#issuecomment-992173903), I'd say she agrees as well. :)

**Comment by osorensen** [comment]
Closed by #238
