### ISSUE TITLE
Platform dependence

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#245]
The item rank functions yield platform dependent results. Previously this has been caused by `Rcpp::setdiff` returning platform dependent results, but this time I'm not so sure. Need to fix this in order to make unit tests with expectations for parameter values, and to do the refactoring in #243.

**Comment by osorensen** [comment]
I have confirmed that this line starts diverging between Windows and Mac in the later iterations. However, it happens before all of `norm_wgt` are equal. Was not able to reproduce the issue when running the sample function directly on the two platforms. Could there be other calls to (overloaded) sample functions that mess things up?

https://github.com/ocbe-uio/BayesMallows/blob/fcea8e4f7c3d363edaf2d23e38d50dcd26e703b0/src/smc_mallows_new_item_rank.cpp#L289

**Comment by osorensen** [comment]
I might be jumping too fast to conclusions. Check if the `N` is equal on the two platforms.

**Comment by osorensen** [comment]
Try to call the Rcpp sample function from only one function, using casting.

**Comment by osorensen** [comment]
On line `289` of `smc_mallows_new_item_rank.cpp` mentioned above, Windows and Mac start diverging at `Time = 19` when run as in this test. The input probabilities are identical, and before `Time = 19` the `index` are always identical.

https://github.com/ocbe-uio/BayesMallows/blob/fcfd664d5262dda67715c825e08639b67f43b1ce/tests/testthat/test-smc_mallows_new_item_rank.R#L117-L126


I checked if this happens because the random number generators starts differing at some point with the script below, by generating 1000 random permutations before checking, but this one was identical across platforms:

```cpp
#include <RcppArmadilloExtensions/sample.h>
// [[Rcpp::depends(RcppArmadillo)]]

arma::vec sample(const arma::vec& x, const int& size, const bool& replace, const arma::vec& probs){
  return Rcpp::RcppArmadillo::sample(x, size, replace, probs);
}
arma::uvec sample(const arma::uvec& x, const int& size, const bool& replace, const arma::vec& probs){
  return Rcpp::RcppArmadillo::sample(x, size, replace, probs);
}

// [[Rcpp::export]]
int sample_r(){
  arma::vec x = arma::regspace(1, 5);
  arma::uvec ux = arma::regspace<arma::uvec>(1, 5);
  arma::vec probs = { .1, .3, .2, .2, .2};
  for(int i = 0; i < 1000; i++){
    sample(x, 5, true, probs);
    sample(ux, 5, true, probs);
  }
  Rcpp::Rcout << sample(ux, 5, true, probs) << std::endl;
  Rcpp::Rcout << sample(x, 5, true, probs) << std::endl;

  return 0;
}

/*** R
set.seed(1)
sample_r()
*/
```

Could still try to remove the overloading, but it might also be that there are tiny numerical differences in `norm_wgt` across platforms which lead to different samples.

**Comment by osorensen** [comment]
Then tried converting `sample.cpp` to this, but that did not solve the issue, so it's probably not caused by the overloading.

```cpp
// [[Rcpp::depends(RcppArmadillo)]]

#include <RcppArmadilloExtensions/sample.h>
arma::vec sample(const arma::vec& x, const int& size, const bool& replace, const arma::vec& probs){
  return Rcpp::RcppArmadillo::sample(x, size, replace, probs);
}
arma::uvec sample(const arma::uvec& x, const int& size, const bool& replace, const arma::vec& probs){
  arma::vec x1 = arma::conv_to< arma::vec >::from(x);
  arma::vec x2 = sample(x1, size, replace, probs);
  return arma::conv_to< arma::uvec >::from(x2);
  //return Rcpp::RcppArmadillo::sample(x, size, replace, probs);
}
```

**Comment by wleoncio** [comment]
Hi Øystein,

Is this still an issue? If so, I'd love to get an MRE (not so easy when the problem is platform-dependent, I know) so I can try to help.

**Comment by osorensen** [comment]
I don't know if it's still a problem, but it would be really great if you could check it out.

**Comment by osorensen** [comment]
Looks like this is not really a platform problem but rather the result of having different C++ compiler flags on different platforms. Details here: https://github.com/RcppCore/RcppArmadillo/issues/430
