### ISSUE TITLE
Prepare CRAN update

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#249]
- [x] Run on rhub with valgrind and sanitizers
- [x] Run win-devel, win-release, win-oldrelease
- [x] Increment version number and update news

**Comment by anjastein** [comment]
Hi! I am currently going through the methodology for the `smc_mallows_new_users` to check it is consistent with my smc methods for clustering (non-BayesMallows work). If there are any changes then they should be minor, but I hope to get an outcome before next Monday!

**Comment by osorensen** [comment]
Thanks for the notice. I'll definitely wait until Monday then.

**Comment by anjastein** [comment]
Outcome: I will be making some incremental changes on Monday!

**Comment by osorensen** [comment]
Then I'm waiting for that :-)

**Comment by osorensen** [comment]
On CRAN now :-)
