### ISSUE TITLE
C++ warnings (comparing unsigned with signed ints)

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#279]
Building the package triggers the following Rcpp warning a couple of times:

> comparison of integer expressions of different signedness: ‘arma::uword’ {aka ‘unsigned int’} and ‘int’

Apparently this happens in at least two places:

- `smc_mallows_new_users.cpp:209`
- `parameterupdates.cpp:16`

Just a minor thing, but probably an easy fix that improves package robustness. :)

**Comment by osorensen** [comment]
Thanks for spotting it, those are important to fix.

**Comment by osorensen** [comment]
Closed by #280
