### ISSUE TITLE
C++ test failures on leapandshift

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#284]
`devtools::test()` is currently failing with the message below:

```
Failure (src/test-leapandshift.cpp:46): leap and shift works
approx_equal(rho_proposal, assumption, "absdiff", 1e-2) isn't true.

Failure (src/test-leapandshift.cpp:47): leap and shift works
std::abs(prob_backward - 0.025) < 1e-2 isn't true.

Failure (src/test-leapandshift.cpp:48): leap and shift works
std::abs(prob_forward - 0.0166667) < 1e-2 isn't true.
```

Tried reducing the tolerance to `1e-2`, but it still fails. Hopefully the fix is no more complicated that that.

Issue surfaced during submission of PR #283.

**Comment by osorensen** [comment]
I do not get this issue, neither on the develop branch nor the master branch.

**Comment by wleoncio** [comment]
I think we need to drop L1 on test-cpp.R first, otherwise L2 doesn't get triggered.

https://github.com/ocbe-uio/BayesMallows/blob/da92fc4e146dc00f7d8ad142f0d2f522eae02f8c/tests/testthat/test-cpp.R#L1

**Comment by osorensen** [comment]
Sure? This is what I get on the develop branch, when L1 is present:

```
> devtools::test()
ℹ Testing BayesMallows
✔ | F W S  OK | Context
✔ |        26 | Testing assess_convergence [0.6s]                     
✔ |        13 | assign_cluster                                        
✔ |         8 | SMC bulletproofing                                    
✔ |        14 | compute_posterior_interval() classes [1.2s]           
✔ |         4 | compute_consensus() classes [0.1s]                    
✔ |        18 | Testing compute_consensus [0.6s]                      
✔ |         5 | compute_mallows_mixtures [0.2s]                       
✔ |        38 | Testing compute_mallows [0.5s]                        
✔ |         8 | compute_posterior_intervals                           
✔ |         6 | Test leap and shift C++                               
✔ |        26 | Testing computation of distance     

```

Looks like leap and shift C++ tests are being run, and they fail on #283 because there `set.seed(1)` has been removed.

**Comment by wleoncio** [comment]
Hmm, on second though you might very well be right. The seed is what's making the test reproducible, after all. I'm trying to remember why I though `set.seed()` was causing the C++ tests not to run, but it could be just me failing to notice both leapandshift and misc tests ran properly. I'll do one more local run and if it looks OK, I'll revert that change in the PR and close this.

**Comment by osorensen** [comment]
It also succeeds in #283 once I add that line back. I do however get a warning about deprecated ggplot2 function, but that's another issue.

**Comment by wleoncio** [comment]
Sorry for the brain fart, closing!
