### ISSUE TITLE
Create webpage

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#290]
Hi @osorensen,

I've been talking with @andreaczhang about the creation of some webpages for the research software hosted on ocbe-uio and we were wondering if we could add one for BayesMallows. Chi has done a great job with the [bayesynergy page](https://ocbe-uio.github.io/bayesynergy/) page, so I was imagining we could have one for BM too. How does that sound?

The idea is to eventually gather links to such webpages on a central https://ocbe-uio.github.io/ site, which will be the main page for the general public to know about the research software we develop.

**Comment by osorensen** [comment]
Hi @wleoncio! This is a great idea, which also has crossed my mind a couple of times.

I've been using pkgdown for my [metagam](https://lifebrain.github.io/metagam/) package, and found it really easy, since it autogenerates all the content based on vignette, documentation, etc. So just go ahead :-)

**Comment by wleoncio** [comment]
Thanks! Yep, that's the general idea: to use pkgdown to create the remaining individual package pages and Quarto for the main page. :)

**Comment by andreaczhang** [comment]
@wleoncio I do not have permission to push local branch to remote here either. Could you give me the right access? Thank you!
