### ISSUE TITLE
NOTE on CRAN submission

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#295]
I get this NOTE which stops resubmission to CRAN. 

```
* checking S3 generic/method consistency ... NOTE
Mismatches for apparent methods not registered:
.compute_cp_consensus:
  function(df, ...)
.compute_cp_consensus.consensus_SMCMallows:
  function(model_fit, burnin)

.compute_cp_consensus:
  function(df, ...)
.compute_cp_consensus.consensus_BayesMallows:
  function(df)

compute_consensus:
  function(model_fit, ...)
compute_consensus.consensus_SMCMallows:
  function(model_fit, type, burnin)

.compute_map_consensus:
  function(df, ...)
.compute_map_consensus.consensus_BayesMallows:
  function(df)

.compute_map_consensus:
  function(df, ...)
.compute_map_consensus.consensus_SMCMallows:
  function(model_fit, burnin)

Apparent methods for exported generics not registered:
  compute_consensus.consensus_SMCMallows
See section 'Registering S3 methods' in the 'Writing R Extensions'
manual.
```

**Comment by osorensen** [comment]
I think all the S3 methods for `consensus_SMCMallows` and `consensus_BayesMallows` need to have a `...` argument to be consistent with their generic, even though the `...` is not used.

So, for example, 

```
.compute_cp_consensus.consensus_BayesMallows:
  function(df)
```

should change signature to 

```
.compute_cp_consensus.consensus_BayesMallows:
  function(df, ...)
```

Could you have a look @wleoncio?

**Comment by wleoncio** [comment]
Also, don't arguments defined in the generic have to also be on the methods? For example, if

```r
.compute_cp_consensus <- function(df, ...) {
  UseMethod(".compute_cp_consensus")
}
```

then 

```r
.compute_cp_consensus.consensus_BayesMallows <- function(df, ...) {
```

is OK, but perhaps

```r
.compute_cp_consensus.consensus_SMCMallows <- function(model_fit, burnin, ...) {
```

Should have `df` instead of `model_fit` as the first argument. Having a hard time testing this since the warning doesn't appear on my local check and Rhub is clogged up (that package doc thing apparently affects "[thousands of packages](https://github.com/r-lib/roxygen2/issues/1491#issue-1780561784)").

**Comment by wleoncio** [comment]
Answering my own question, I've created a test package with a `print()` method and got this warning:

![bilde](https://github.com/ocbe-uio/BayesMallows/assets/8234768/5880ac6e-9d9f-423a-9fa3-6ed5dafd78d7)

The warning only went away when `print.meme()` had argument list {x, ...}, so I guess I'll propose the arg change to solve this issue as well. 🤞🏽

**Comment by osorensen** [comment]
From https://adv-r.hadley.nz/s3.html


> There is one exception to this rule: if the generic has ..., the method can contain a superset of the arguments. This allows methods to take arbitrary additional arguments. The downside of using ..., however, is that any misspelled arguments will be silently swallowed72, as mentioned in Section [6.6](https://adv-r.hadley.nz/functions.html#fun-dot-dot-dot).

**Comment by osorensen** [comment]
So function(x, what, ...) should work for print.meme in your example?

**Comment by wleoncio** [comment]
Yep, that works too. In other words, a method's arguments should be a superset of the generic's arguments.

**Comment by osorensen** [comment]
> Yep, that works too. In other words, a method's arguments should be a superset of the generic's arguments.

If the generic has ... as argument, but otherwise they must exactly match.

**Comment by wleoncio** [comment]
Version 1.3.1 is on CRAN with fixes, so I suppose it's alright to close this issue.
