### ISSUE TITLE
CRAN failure

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#297]
Remember that strange change you asked about @wleoncio?

https://www.stats.ox.ac.uk/pub/bdr/LTO/BayesMallows.out

**Comment by wleoncio** [comment]
Yep, that's the one. If I recompile the current master version I get this:

![bilde](https://github.com/ocbe-uio/BayesMallows/assets/8234768/82b6f67b-9d5a-4d06-ae8b-6e46b19de00e)

If that also happens on your (mac?) machine, perhaps that's all we need to do?

**Comment by osorensen** [comment]
Thanks for checking! It seems like my Mac machine has caused this.

![image](https://github.com/ocbe-uio/BayesMallows/assets/21175639/2769a36c-fffd-4b9c-9ab0-8d2a5b919363)

Since I'm the maintainer, I'll have to submit the update to CRAN. Will re-build it on my Windows machine when I come home in the evening.

**Comment by wleoncio** [comment]
I think it's worth a try, I bet it just recompiles everything. If the Windows build doesn't work, let me know and I can just do it on Linux here.

Apropos, as I was fixing that roxygen issue on other packages, I noticed that https://win-builder.r-project.org/ was detecting some issues that https://r-hub.github.io/rhub/ wasn't, particulary for R-devel on Windows, so I started making it a habit of checking the package on that platform before submitting.

**Comment by osorensen** [comment]
I get the same thing on Windows as on Mac. Which version of testthat are you running? I'm on the latest, 3.1.10.

**Comment by osorensen** [comment]
I opened an [issue in testthat](https://github.com/r-lib/testthat/issues/1849). We do have two weeks to fix it, so it's possible to wait at least a little bit.

**Comment by wleoncio** [comment]
Same here, 3.1.10. The good news is that if this is still the CRAN submission fixing #292, they initially give us a "few months" to fix. Did we get a new deadline since that fix was already published, then? 😬

**Comment by osorensen** [comment]
No, that submission is already on CRAN and that issue is fixed. It passed with no problems. This issue arised with the additional C++ tests that Brian Ripley is running on packages that are already on CRAN. So this will be yet another package update. We got two weeks to fix it, so I suggest we spend a week trying to understand what's going on, and then resubmit with a fix.

**Comment by wleoncio** [comment]
OK, got it, I'll give this higher priority, then. 👍🏽

**Comment by osorensen** [comment]
Did you check on windows this morning? The check was all fine, except for a warning that the version number is already on CRAN. So that test does not catch this issue.

**Comment by wleoncio** [comment]
Yep, sent three requests to https://win-builder.r-project.org/upload.aspx before a 9:00 meeting. Sorry, I forgot the reports were gonna be sent to you 🤦🏽. Kind of annoying having to chase reproducibility around. The version number is the same, but that tarball actually contains [the change I mentioned earlier](https://github.com/ocbe-uio/BayesMallows/issues/297#issuecomment-1689488599), so maybe we could just try submitting that one instead? I'll open a PR so we have a branch to work together on, anyway.

**Comment by osorensen** [comment]
Sounds like a good idea to submit what you have. Then we have a fix for this issue, and can spend time later figuring out what happens when I'm compiling. Might be a compiler issue?

**Comment by wleoncio** [comment]
Yep, looking at the compilers may be the best thing to do next. CRAN checks seem to use clang 10 or 13 for macOS r-oldrel and 14 for the rest, which version are you using there?

**Comment by osorensen** [comment]
Seems like I'm using clang 14, like CRAN checks, but unlike professor Ripley.

```zsh
(base) oyss@eduroam-193-157-194-254 ~ % gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
```

**Comment by osorensen** [comment]
So if you could run `R CMD build` on the package now, then I think the easiest is if you e-mail me the tarball. Then I can upload, and click on the links on the confirmatory e-mail.

**Comment by wleoncio** [comment]
OK, done in a few minutes.
