### ISSUE TITLE
psi variable not used in compute_mallows?

### ISSUE THREAD

**Issue by lorenzo-zuccato** [ocbe-uio/BayesMallows#313]
Hi, I have noticed that the psi parameter is not used anywhere in the function compute_mallows. I think it should be passed to the run_mcmc function, otherwise it will always use 10 as fixed value. Is there a reason for this?

**Comment by osorensen** [comment]
Thanks @lorenzo-zuccato, that's a very good catch.

**Comment by osorensen** [comment]
Here is a test I've made after properly propagating the `psi` argument to `run_mcmc`. It seems to me correct, in light of the [animation on Wikipedia](https://en.wikipedia.org/wiki/Dirichlet_distribution#/media/File:LogDirichletDensity-alpha_0.3_to_alpha_2.0.gif), that with lower `psi` we get closer to hard clustering, and with increasing `psi` we get soft clustering. 

``` r
library(BayesMallows)
library(ggplot2)
library(patchwork)
set.seed(123)
mixture_model1 <- compute_mallows(
  rankings = sushi_rankings[1:100, ], n_clusters = 3,
  include_wcd = TRUE, save_clus = TRUE, nmc = 100, psi = 100
)

set.seed(123)
mixture_model2 <- compute_mallows(
  rankings = sushi_rankings[1:100, ], n_clusters = 3,
  include_wcd = TRUE, save_clus = TRUE, nmc = 100, psi = .1
)

(assess_convergence(mixture_model1, parameter = "cluster_probs") +
  ggtitle("psi = 100")) +
  (assess_convergence(mixture_model2, parameter = "cluster_probs") +
     ggtitle("psi = 0.1"))
```

![](https://i.imgur.com/nudLAdw.png)

<sup>Created on 2023-10-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by osorensen** [comment]
Thanks again @lorenzo-zuccato, this is fixed now, and will be on CRAN in a few days, hopefully.
