### ISSUE TITLE
S3 method compute_posterior_intervals() inconsistent with rest of the package

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#318]
S3 method compute_posterior_intervals() is not called directly for SMC Mallows objects. Instead it is called internally by compute_posterior_intervals_alpha() and compute_posterior_intervals_rho(). For consistency with the other parts of the package, I think we should do otherwise, but then we get a bigger job.

_Originally posted by @osorensen in https://github.com/ocbe-uio/BayesMallows/issues/317#issuecomment-1748089981_

**Comment by osorensen** [comment]
Thanks for making the issues!
