### ISSUE TITLE
Is boolean variable _clustering_ used in function augment_pairwise?

### ISSUE THREAD

**Issue by lorenzo-zuccato** [ocbe-uio/BayesMallows#325]
Hi! I see that the argument "clustering" is passed as boolean variable to the function augment_pairwise, but it is not actually used in the function. Is the function doing what it is supposed to do anyway? Thanks!

**Comment by osorensen** [comment]
Thanks for spotting this. It is an error that the argument is included there, and the function does what it is to do. I'll remove it now.

**Comment by lorenzo-zuccato** [comment]
Thank you :)
