### ISSUE TITLE
What is the point of obs_freq in rmallows?

### ISSUE THREAD

**Issue by lorenzo-zuccato** [ocbe-uio/BayesMallows#337]
Hi! As the title says, could someone kindly tell me what is the point of passing obs_freq to the simulation algorithm rmallows? As far as I understood rmallows can sample from the Mallows model with given parameters, and the obs_freq is only passed to the rank_dist_sum function. However since we are passing rho0 as rankings to it, I think the variable n in rank_dist_vec is always equal to 1.
If what I said makes sense it would make sense to pass ones(1) to rank_dist_sum instead of asking the user to provide obs_freq.
Please correct me if I'm wrong!

**Comment by osorensen** [comment]
Thanks again @lorenzo-zuccato, it is very useful that you read our code. Again, you're absolutely right that this argument is not needed, since it's fixed to 1 wherever the function is called. I'll clean it up now.

**Comment by lorenzo-zuccato** [comment]
Thanks! :)
