### ISSUE TITLE
Simplify arguments to compute_mallows()

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#340]
compute_mallows() currently has 29 arguments:

``` r
library(BayesMallows)
length(formals(compute_mallows))
#> [1] 29
```

<sup>Created on 2023-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is actually way too much, and it could be simplified by grouping them, similar to what is done in several other packages. Here is an example of a grouping:

- Prior parameters could be specified by a call to a function named something like `mallows_prior()`, with reasonable default arguments. This would reduce the 3 arguments `lambda`, `alpha_max`, and `psi` to 1.
- Obscure MCMC parameters which most users won't touch could be specified by a call to something like `mallows_options()`, with reasonable default arguments. This would reduce the 9 arguments `clus_thin`, `leap_size`, `swap_leap`, `rho_thinning`, `alpha_prop_sd`, `alpha_jump`, `include_wcd`, `save_aug`, and `aug_thinning` to 1. Could optionally also include `nmc` here.
- Initial values could be specified with something like `mallows_init()`, specifying initial values for `rho_init` and `alpha_init`, reducing from 2 to 1.

Since this would be a (very) breaking change, I would have to rewrite the R Journal paper into an update vignette, which has the added benefit that it would look good on the package website.

**Comment by wleoncio** [comment]
I'm 100% in favor of reducing the number of arguments ([Clean Code](https://gpcoder.gitbook.io/clean-code/the-key-principles-of-clean-code/functions#prefer-fewer-arguments) argues that even 4 is too many 😅 ). "Advanced options" could be also grouped under one list, like many other function (e.g. `optim()`) do.

**Comment by osorensen** [comment]
Wonderful that you agree! I actually got inspired to do this after start to read the book [Clean Code](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882)
