### ISSUE TITLE
 No visible license

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#36]
# Summary

The software license is hidden inside the DESCRIPTION file; that doesn't spark joy in the GitHub gods.

This is nothing major, just a small thing to tacke if someone has 5 minutes available in their working day. I can also do the changes myself if someone reponsible for the package greenlights me.

# Issue

One can see the package is licensed under GPL-3 by looking in the [DESCRIPTION](https://github.com/ocbe-uio/BayesMallows/blob/master/DESCRIPTION) file, but unfortunately GitHub is not that smart, and the package shows up as missing a license on https://github.com/ocbe-uio/BayesMallows/community.

As a result, the licence doesn't show up on the top bar of the package's repository or on ocbe-uio's front page. Compare
![bilde](https://user-images.githubusercontent.com/8234768/75667564-2da76f00-5c78-11ea-8e7b-bbeef37dc3be.png)
with
![bilde](https://user-images.githubusercontent.com/8234768/75667940-c8a04900-5c78-11ea-8b0a-546ad3bea850.png)
and
![bilde](https://user-images.githubusercontent.com/8234768/75667794-7fe89000-5c78-11ea-941e-30c1fadbc958.png)
with
![bilde](https://user-images.githubusercontent.com/8234768/75667980-d655ce80-5c78-11ea-9be2-4917d2525702.png)

# How to fix

This is easy to fix, one just needs to add the proper LICENSE file to the package root. If I recall correctly, it's also best to add LICENSE to the .Rbuildignore file to avoid R CMD check bothering you about duplicated licenses or something like that.

**Comment by osorensen** [comment]
Closing this now. Thanks again!
