### ISSUE TITLE
Validate implementation for partial rankings

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#378]
Based on discussions with Marta. Reproduce results in JMLR paper. Data are here.

```r
library(RankAggreg) 
data(geneLists)
```

**Comment by osorensen** [comment]
The JMLR paper says this:

<img width="766" alt="image" src="https://github.com/ocbe-uio/BayesMallows/assets/21175639/2c5b40c3-b43c-4faf-9b05-8948393b3b5a">

I find it hard to believe they actually used L=40.

**Comment by crispinomarta** [comment]
This is weird.... I do not remember who wrote that section and run the
final codes: maybe Valeria must be involved in this investigation?

Il giorno ven 16 feb 2024 alle ore 12:05 Øystein Sørensen <
***@***.***> ha scritto:

**Comment by wleoncio** [comment]
Just dropping in to add a direct link to the paper (it's also on the README, FWIW): https://jmlr.org/papers/v18/15-481.html
