### ISSUE TITLE
Heat plot is wrong with thinning

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#381]
Seems like we're dividing by the `nmc` parameter provided in `compute_options` and not by the actual number of stored iterations. Thanks to Marta for discovering.

``` r
library(BayesMallows)
set.seed(1)
mod <- compute_mallows(
  data = setup_rank_data(potato_visual),
  compute_options = set_compute_options(nmc = 10000, burnin = 400)
  )

plot(mod, parameter = "rho", items = 12)
```

![](https://i.imgur.com/UpntpoZ.png)

``` r
heat_plot(mod)
```

![](https://i.imgur.com/5RMJyRl.png)

``` r

mod <- compute_mallows(
  data = setup_rank_data(potato_visual),
  compute_options = set_compute_options(nmc = 10000, burnin = 400, rho_thinning = 10)
)

plot(mod, parameter = "rho", items = 12)
```

![](https://i.imgur.com/QSOoOBu.png)

``` r
heat_plot(mod)
```

![](https://i.imgur.com/m7mWCIe.png)

<sup>Created on 2024-02-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by osorensen** [comment]
Good now

``` r
library(BayesMallows)
set.seed(1)
mod <- compute_mallows(
  data = setup_rank_data(potato_visual),
  compute_options = set_compute_options(nmc = 10000, burnin = 400)
  )

plot(mod, parameter = "rho", items = 12)
```

![](https://i.imgur.com/F1OYI1F.png)

``` r
heat_plot(mod)
```

![](https://i.imgur.com/pIzKPkd.png)

``` r

mod <- compute_mallows(
  data = setup_rank_data(potato_visual),
  compute_options = set_compute_options(nmc = 10000, burnin = 400, rho_thinning = 10)
)

plot(mod, parameter = "rho", items = 12)
```

![](https://i.imgur.com/S7XOWOV.png)

``` r
heat_plot(mod)
```

![](https://i.imgur.com/U5thzMC.png)

<sup>Created on 2024-02-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by wleoncio** [comment]
![](https://i.imgflip.com/64icd0.jpg)

**Comment by osorensen** [comment]
Look at the probabilities legend at the lower plot

**Comment by osorensen** [comment]
## Before 
<img width="113" alt="image" src="https://github.com/ocbe-uio/BayesMallows/assets/21175639/b4fd0c47-acc4-4220-a5ab-570de6ffb4bd">

## After
<img width="98" alt="image" src="https://github.com/ocbe-uio/BayesMallows/assets/21175639/e0cf6a59-c8db-4b3b-8728-190665104b17">

**Comment by wleoncio** [comment]
Oh good, thanks for pointing that out. I was obsessing with the plots and totally forgot to look at the legends.
