### ISSUE TITLE
Consistency check for updated pairwise preferences

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#404]
Currently with existing users providing updated preferences, all are treated as inconsistent. Fix this be writing a function which checks for consistency.

**Comment by crispinomarta** [comment]
It is sufficient to check if the directed graph of pairwise preferences is
acyclic (if it is a DAG -directed acyclic graph - then the preferences are
consistent).
I think that in the *igraph *package there's a function which does exactly
this: *is_dag.*


Il giorno ven 15 mar 2024 alle ore 15:42 Øystein Sørensen <
***@***.***> ha scritto:

**Comment by osorensen** [comment]
Thanks! But I'm not sure we're talking about the same thing. I'm thinking of the SMC methodology, where an existing user may provide additional pairwise preferences at some time t. The thing I want to check is if the augmented ranking from time t-1 for this user is consistent with the pairwise preferences at time t.

For partial rankings this is quite straightforward, cf. screenshot below from Anja Stein's PhD:

<img width="1374" alt="image" src="https://github.com/ocbe-uio/BayesMallows/assets/21175639/d0626f34-57dd-441a-a105-f5a6dafc0bd8">

**Comment by osorensen** [comment]
It's not too hard, but has to be implemented. I think this algorithm will do the job (sorry about the notation):

<img width="668" alt="image" src="https://github.com/ocbe-uio/BayesMallows/assets/21175639/91fb4061-4545-4f83-a2e7-bc0cbe621ee3">
