### ISSUE TITLE
Sampling mixtures

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#42]
It would be nice to extend `sample_mallows()` so we can sample from mixtures, with K=1 being the special case of a single cluster.

**Comment by MartaCrispino** [comment]
When working on this, I suggest to think about the fact that it is possible, and much more efficient, to sample exactly (and not using the MH) in some cases (for instance when n is small).

**Comment by osorensen** [comment]
I think this feature is best obtained on the user side, simply by calling `sample_mallows()` once for each set of cluster parameters.
