### ISSUE TITLE
Speed up computation

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#43]
Speed up the algorithms by using the frequencies of the observed rankings (introduce a weight equal to the number of times the exact pattern occurs in the data).

**Comment by osorensen** [comment]
This issue is close by #50

**Comment by MartaCrispino** [comment]
This is a great extension! Cristina (and I agree) suggests to change the argument name, since "weights" is easily confused with the weights of the mixture model. 

Marta

**Comment by osorensen** [comment]
I agree, @MartaCrispino . Do you have a suggestion for another name? 

Some possibilties I can think of are "multiplier", "case_weight", "sample_weight"? But not sure if they are good.

**Comment by MartaCrispino** [comment]
Maybe obs_freq?

**Comment by osorensen** [comment]
That sounds good!

**Comment by osorensen** [comment]
Pull request #51 closes this issue.
