### ISSUE TITLE
obs_freq error

### ISSUE THREAD

**Issue by PaulCristina** [ocbe-uio/BayesMallows#57]
I'm trying to use obs_freq to speed up the process but I'm getting an error "obs_freq must be of same length as the number of rows in rankings" and indeed the number of rows is different, not sure why, attached code and data.

Also there is a way to make "compute_mallows" run parallel? It takes a very long time even with a small dataset.

Thank you
[pairwise_comparison.zip](https://github.com/ocbe-uio/BayesMallows/files/5879680/pairwise_comparison.zip)

source("/home/paulc/projects_Paul/32_recosystem_gather_data/R/libraries/librariesUsed.R")
#> [1] "Read libraries that will be used ..."
#> Loading required package: DBI
#> 
#> Attaching package: 'datetimeutils'
#> The following objects are masked from 'package:lubridate':
#> 
#>     mday, mday<-, month, year
#> Warning in fun(libname, pkgname): couldn't connect to display ":0"
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: CentOS Linux 7 (Core)
#> 
#> Matrix products: default
#> BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] parallel  stats     graphics  grDevices datasets  utils     methods  
#> [8] base     
#> 
#> other attached packages:
#>  [1] DALEX_2.0.1              RColorBrewer_1.1-2       viridis_0.5.1           
#>  [4] viridisLite_0.3.0        ClusterR_1.2.2           gtools_3.8.2            
#>  [7] fpc_2.2-9                factoextra_1.0.7         cluster_2.1.0           
#> [10] pROC_1.16.2              ROCR_1.0-11              future.batchtools_0.10.0
#> [13] doRNG_1.8.2              rngtools_1.5             progressr_0.7.0         
#> [16] doFuture_0.12.0          future_1.21.0            doParallel_1.0.16       
#> [19] iterators_1.0.13         foreach_1.5.1            stringdist_0.9.6.3      
#> [22] ggrepel_0.9.0            plotly_4.9.2.2           cowplot_1.1.1           
#> [25] gridExtra_2.3            Rtsne_0.15               workflows_0.2.1         
#> [28] tune_0.1.2               rsample_0.0.8            parsnip_0.1.4           
#> [31] modeldata_0.1.0          infer_0.5.3              dials_0.0.9             
#> [34] scales_1.1.1             broom_0.7.3              tidymodels_0.1.2        
#> [37] gower_0.2.2              caret_6.0-86             lattice_0.20-41         
#> [40] benford.analysis_0.1.5   robustbase_0.93-6        correlation_0.5.0       
#> [43] corrplot_0.84            corrr_0.4.3              yardstick_0.0.7         
#> [46] recipes_0.1.15           dlookr_0.3.14            mice_3.12.0             
#> [49] inspectdf_0.0.9          rcompanion_2.3.26        summarytools_0.9.8      
#> [52] here_1.0.1               arrow_2.0.0              feather_0.3.5           
#> [55] igraph_1.2.6             BayesMallows_1.0.0       text2vec_0.6            
#> [58] rsparse_0.4.0            magrittr_2.0.1           matrixStats_0.57.0      
#> [61] Matrix_1.2-18            data.table_1.13.6        forcats_0.5.0           
#> [64] dplyr_1.0.3              purrr_0.3.4              readr_1.4.0             
#> [67] tidyr_1.1.2              tibble_3.0.5             tidyverse_1.3.0         
#> [70] tictoc_1.0               jsonlite_1.7.2           tm_0.7-8                
#> [73] NLP_0.2-1                stringr_1.4.0            stringi_1.5.3           
#> [76] datetimeutils_0.4-0      eeptools_1.2.4           ggplot2_3.3.3           
#> [79] anytime_0.3.9            lubridate_1.7.9.2        mongolite_2.2.1         
#> [82] RMySQL_0.10.21           DBI_1.1.0               
#> 
#> loaded via a namespace (and not attached):
#>   [1] vcd_1.4-8            Hmisc_4.4-2          class_7.3-17        
#>   [4] lmtest_0.9-38        rprojroot_2.0.2      crayon_1.3.4        
#>   [7] rbibutils_2.0        MASS_7.3-53          nlme_3.1-149        
#>  [10] backports_1.2.1      reprex_0.3.0         rlang_0.4.10        
#>  [13] readxl_1.3.1         nloptr_1.2.2.2       proto_1.0.0         
#>  [16] bit64_4.0.5          glue_1.4.2           base64url_1.4       
#>  [19] classInt_0.4-3       tcltk_4.0.3          haven_2.3.1         
#>  [22] tidyselect_1.1.0     rio_0.5.16           zoo_1.8-8           
#>  [25] chron_2.3-56         xtable_1.8-4         evaluate_0.14       
#>  [28] quantmod_0.4.18      Rdpack_2.1           cli_2.2.0           
#>  [31] rstudioapi_0.13      furrr_0.2.1          sp_1.4-4            
#>  [34] DiceDesign_1.8-1     rpart_4.1-15         tinytex_0.28        
#>  [37] prettydoc_0.4.0      xfun_0.19            parameters_0.10.1   
#>  [40] ggfittext_0.9.0      expm_0.999-5         listenv_0.8.0       
#>  [43] png_0.1-7            ipred_0.9-9          withr_2.4.0         
#>  [46] slam_0.1-48          plyr_1.8.6           cellranger_1.1.0    
#>  [49] e1071_1.7-4          coda_0.19-4          pillar_1.4.7        
#>  [52] multcomp_1.4-15      fs_1.5.0             kernlab_0.9-29      
#>  [55] flexmix_2.3-17       TTR_0.24.2           partykit_1.2-11     
#>  [58] xts_0.12.1           vctrs_0.3.6          ellipsis_0.3.1      
#>  [61] generics_0.1.0       gsubfn_0.7           nortest_1.0-4       
#>  [64] lava_1.6.8.1         tools_4.0.3          foreign_0.8-80      
#>  [67] mlapi_0.1.0          munsell_0.5.0        compiler_4.0.3      
#>  [70] abind_1.4-5          DescTools_0.99.39    prodlim_2019.11.13  
#>  [73] DMwR_0.4.1           arm_1.11-2           gld_2.6.2           
#>  [76] carData_3.0-4        renv_0.12.3          lazyeval_0.2.2      
#>  [79] car_3.0-10           latticeExtra_0.6-29  brew_1.0-6          
#>  [82] effectsize_0.4.1     checkmate_2.0.0      rapportools_1.0     
#>  [85] rmarkdown_2.6        openxlsx_4.2.3       sandwich_3.0-0      
#>  [88] statmod_1.4.35       webshot_0.5.2        pander_0.6.3        
#>  [91] survival_3.2-7       yaml_2.2.1           prabclus_2.3-2      
#>  [94] htmltools_0.5.1.1    memoise_1.1.0        modeltools_0.2-23   
#>  [97] lgr_0.4.1            batchtools_0.9.15    gmp_0.6-1           
#> [100] digest_0.6.27        assertthat_0.2.1     RhpcBLASctl_0.20-137
#> [103] rappdirs_0.3.1       bayestestR_0.8.0     RSQLite_2.2.1       
#> [106] sqldf_0.4-11         Exact_2.1            blob_1.2.1          
#> [109] lhs_1.1.1            splines_4.0.3        Formula_1.2-4       
#> [112] hms_1.0.0            modelr_0.1.8         colorspace_2.0-0    
#> [115] base64enc_0.1-3      libcoin_1.0-7        inum_1.0-1          
#> [118] nnet_7.3-14          mclust_5.4.7         Rcpp_1.0.6          
#> [121] coin_1.3-1           mvtnorm_1.1-1        GPfit_1.0-8         
#> [124] multcompView_0.1-8   fansi_0.4.2          parallelly_1.22.0   
#> [127] ModelMetrics_1.2.2.2 R6_2.5.0             grid_4.0.3          
#> [130] lifecycle_0.2.0      EMT_1.1              rootSolve_1.8.2.1   
#> [133] zip_2.1.1            curl_4.3             pryr_0.1.4          
#> [136] minqa_1.2.4          TH.data_1.0-10       htmlwidgets_1.5.3   
#> [139] rvest_0.3.6          globals_0.14.0       insight_0.11.1      
#> [142] lmom_2.8             htmlTable_2.1.0      codetools_0.2-16    
#> [145] prettyunits_1.1.1    dbplyr_2.0.0         gtable_0.3.0        
#> [148] stats4_4.0.3         httr_1.4.2           highr_0.8           
#> [151] KernSmooth_2.23-17   progress_1.2.2       diptest_0.75-7      
#> [154] reshape2_1.4.4       magick_2.5.2         timeDate_3043.102   
#> [157] xml2_1.3.2           smbinning_0.9        RcmdrMisc_2.7-1     
#> [160] boot_1.3-25          kableExtra_1.3.1     lme4_1.1-26         
#> [163] float_0.2-4          DEoptimR_1.0-8       bit_4.0.4           
#> [166] jpeg_0.1-8.1         pkgconfig_2.0.3      maptools_1.0-2      
#> [169] gbRd_0.4-11          knitr_1.30

df.pairwise_comparison <- readRDS(file = "/home/paulc/projects_Paul/32_recosystem_gather_data/R/data/processed/pairwise_comparison.rds")

seed = 2020

# convert data to matrix
cl <- makeCluster(10)
df.init_rank <- generate_initial_ranking(df.pairwise_comparison, cl = cl)

alpha_vector <- seq(from = 0, to = 10, by = 0.5)
n_items <- dim(df.init_rank)[2]
metric <- "footrule"
degree <- 10

fit1 <- estimate_partition_function(method = "importance_sampling",
                                    alpha_vector = alpha_vector,
                                    n_items = n_items,
                                    metric = metric,
                                    nmc = 1000L,
                                    degree = degree,
                                    cl = cl,
                                    seed = seed)

stopCluster(cl)

obs_freq <- rank_freq_distr(df.init_rank)
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2

dim(obs_freq)
#> [1] 3589  101

dim(df.init_rank)
#> [1] 5552  100

model_fit <- compute_mallows(rankings = df.init_rank,
                            preferences = df.pairwise_comparison,
                            metric = metric,
                            save_aug = FALSE,
                            validate_rankings = FALSE,
                            nmc = 1500L,
                            alpha_jump = 1000L,
                            logz_estimate = fit1,
                            obs_freq = obs_freq,
                            verbose = TRUE,
                            seed = seed)
#> Error in compute_mallows(rankings = df.init_rank, preferences = df.pairwise_comparison, : obs_freq must be of same length as the number of rows in rankings

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by osorensen** [comment]
Thanks for reaching out, and thanks for such a clear reproducible example!

Unfortunately, the `rank_freq_distr` function is not very mature at the moment, and is not define to work with preference data yet. I suggest using tidyverse tools for counting the number of unique sets of pairwise preferences per user, and then provide this to the obs_freq argument. 

Here is my suggested solution as of now, not too well commented since I do not have too much time ;-) 

Please get back to me if anything is unclear:

```r
library(BayesMallows)
library(tidyverse)
df.pairwise_comparison <- readRDS("Downloads/pairwise_comparison") %>% 
  as_tibble()

# I keep only a subset of your data to make it faster
df.pairwise_comparison <- df.pairwise_comparison[1:3000, ]

# Unfortunately, the rank_freq_distr() function is not yet designed
# to work with preference data, so I suggest a workaround instead.
# First, reduce the dataset by finding the unique number of patterns
# Generate transitive closure
tc <- generate_transitive_closure(df.pairwise_comparison) %>% 
  as_tibble()
# Sort by bottom item first and then top item, and then find a unique string of rank patterns
df1 <- tc %>%
  arrange(assessor, top_item, bottom_item) %>%
  group_by(assessor) %>%
  summarise(
    concat_ranks = paste(c(bottom_item, top_item), collapse = ","),
    bottoms = list(bottom_item),
    tops = list(top_item),
    .groups = "drop"
    )

weight_df <- df1 %>% 
  group_by(concat_ranks) %>% 
  summarise(
    num_assessors = n(),
    assessor_ids = list(assessor), 
    .groups = "drop"
  )

# Create a new preference dataset, with only one group per unique preference set
df2 <- df1 %>% 
  group_by(concat_ranks) %>% 
  filter(row_number() == 1) %>% 
  ungroup() %>% 
  inner_join(weight_df, by = "concat_ranks") %>% 
  unnest(cols = c(bottoms, tops)) %>% 
  rename(
    bottom_item = bottoms,
    top_item = tops,
    obs_freq = num_assessors
  )

tc2 <- df2 %>% 
  select(assessor, bottom_item, top_item) %>% 
  generate_transitive_closure()


# Note that we have reduced the number of rows
dim(tc2)
dim(tc)
# Also note that df2 was already the transitive closure
# We just run it through the generate_transitive_closure() function
# to get the right S3 class
all.equal(
  select(df2, assessor, bottom_item, top_item),
  as_tibble(tc2)
)
# We thus define obs_freq from df2
obs_freq <- df2 %>% 
  distinct(assessor, num_assessors) %>% 
  pull(num_assessors)

# Initial ranking
rankings <- generate_initial_ranking(tc2)

dim(rankings)

n_items <- ncol(rankings)

fit1 <- estimate_partition_function(method = "importance_sampling",
                                    alpha_vector = seq(from = 0, to = 10, by = 0.5),
                                    n_items = n_items,
                                    metric = "footrule",
                                    nmc = 1000L,
                                    degree = 7)



model_fit_rep <- compute_mallows(rankings = rankings,
                                 preferences = tc2,
                                 obs_freq = obs_freq,
                                 logz_estimate = fit1,
                                 nmc = 100)



```


As for running compute_mallows in parallel, I'm afraid that's complicated by the fact that the MCMC algorithm is by nature sequential. You could however make many individual MCMC runs in parallel, and then combine the samples manually.

**Comment by osorensen** [comment]
I also suggest taking a look at the examples in `help("obs_freq")`, which parts of my solution is based on.

**Comment by PaulCristina** [comment]
Thank you for your help
