### ISSUE TITLE
Dependence on ggmcmc

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#59]
@cmollica, you probably noticed we both got an e-mail from Prof. Ripley regarding the dependency on the ggmcmc package, which will be removed from CRAN. He writes that packages depending on ggmcmc will also be kicked out, and as far as I have heard, these things might happen relatively fast.

BayesMallows depends on ggmcmc through PLMIX (PLMIX lists ggmcmc in Imports), and since you are the maintainer of PLMIX, I was wondering if you have any chance of removing the dependency of PLMIX on ggmcmc over the next few weeks?

As for BayesMallows, I don't think any changes are needed if PLMIX's dependence on ggmcmc is removed.

**Comment by cmollica** [comment]
Dear Oystein,

yes, I received his mail. Of course, I am going to work on that new weeks to avoid problems on our package, even if no functions from ggmcmc are used in BayesMallows through PLMIX. Thanks for stressing the issue.

Cristina

**Comment by osorensen** [comment]
Thanks! I think the problem is that even if BayesMallows does not use ggmcmc, if PLMIX fails because ggmcmc fails, then he might kick out BayesMallows as well, so good to hear that you will be working on it :-)

**Comment by osorensen** [comment]
Seems like the ggmcmc maintainer solved the issue.
