### ISSUE TITLE
Initial commit for the SMC-Mallows branch

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#63]
- [x] Create `smc-mallows` branch (or some other meaningful name)
- [x] Copy `run_script_smc_mallows_complete.R`
- [x] Check cleanly
- [x] Open PR

**Comment by wleoncio** [comment]
Clean-ish check achieved by commit a726e4ef591f8b98791e90c0c913f9125bd2e4b9. See commit message for more details, but the gist of it is that I just need to comment out some functions and then we're good to continue.

Each new file contains some commented-out code with a test script. This shall be incorporated into the package's unit tests (see Issue #65).

**Comment by wleoncio** [comment]
Just realized I've been commiting to `smc-mallows` instead of a feature branch that would be merged into `smc-mallows` through a PR. 🤦🏽  I got a bit confused by the absence of a `develop` branch. 

@osorensen, as I work on the current issue and others related to the SMC-Mallows integration (e.g. #65 and #66), do you have a preference whether I should:

1. open PRs merging `issue-*` into `smc-mallows` or
2. always work on `smc-mallows` and open PRs merging into `master`?

Sorry for only bringing this up now, I guess I got a bit too excited to start without considering the standard Git workflow followed by BayesMallows.

**Comment by osorensen** [comment]
@wleoncio , I actually don't have a preference for either. Do whatever works best for you :-)
