### ISSUE TITLE
Update authorship

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#72]
- [x] Add @anjastein as author of SMC functions (anyone else?)
- [x] Add @anjastein and @wleoncio to DESCRIPTION ("aut" and "trl"?)

**Comment by osorensen** [comment]
Agreed! Will do when I have time

**Comment by wleoncio** [comment]
Thanks for the approval, @osorensen. I got my hands on the code right now, can make the change myself if that's OK.

**Comment by osorensen** [comment]
Please go ahead!
