### ISSUE TITLE
SMC main function needs reparametrization

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#87]
The overhaul of `metropolis_hastings_alpha()` (see commit df2f40aa296e1de84483464396c4f9b77baa45b8) broke the `smc_mallows_new_users_complete()` function, which still uses the parameterization of the old version:

https://github.com/ocbe-uio/BayesMallows/blob/124ebe964d7d8147286eeebb61b0eabc5a05394c/R/smc_mallows_new_users_complete.R#L106-L111

The difference is basically in the absence of these mandatory arguments:

- `alpha_prop_sd`
- `lambda`
- `alpha_max`

So there are at least three solutions here:

1. Updating `smc_mallows_new_users_complete()` to pass these arguments
2. Adding default values for these arguments on `metropolis_hastings_alpha()`
3. Adding code to calculate these arguments inside `metropolis_hastings_alpha()`

Co-assigning Anja here for help on choosing a preferred method and advice on how to calculate these arguments (I found no clue in the code of `smc_mallows_new_users_complete()`)

**Comment by anjastein** [comment]
Hello,
`alpha_prop_sd`, `lambda` and `alpha_max` are the same arguments used in the `compute_mallows` function in the BayesMallows package to account for the parameters for the prior distribution of alpha. We can use the default values for these arguments in `compute_mallows` and add them as the extra input arguments for `smc_mallows_new_users_complete()` to keep things simple.

**Comment by wleoncio** [comment]
Fixed on d365ccb394a0ef8b7e81ad9b412e95049a989c82 (to be pushed when #81 is closed).
