### ISSUE TITLE
Improve SMC object classes

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#90]
- [x] smc_mallows_new_users_complete.cpp
- [x] smc_leap_and_shift_probs.cpp

**Comment by wleoncio** [comment]
Hi @osorensen!

Thanks to your tip, I managed to replace several instances of `Rcpp::sample` with `arma::rand`, except for the following line:

https://github.com/ocbe-uio/BayesMallows/blob/444de46243cafef7ba86cebb2b0dea9c686237e2/src/smc_mallows_new_users_complete.cpp#L150

The problem basically being the sampling with replacement here. Do you know if there's an Armadillo equivalent to the R command `sample(N, replacement=TRUE)`?

**Comment by wleoncio** [comment]
Wait, I may have found something useful:

![image](https://user-images.githubusercontent.com/8234768/123045112-ce381a00-d3fa-11eb-937e-1338a78f9224.png)

**Comment by osorensen** [comment]
That looks good!!

**Comment by osorensen** [comment]
And this looks reassuring, but these numbers are all uniformly distributed; is that sufficient, or do you also need to supply a probability vector?

``` r
Rcpp::cppFunction(depends = 'RcppArmadillo',
                  'arma::imat f(int n, int a, int b){arma::imat x = arma::randi(n, arma::distr_param(a, b)); return(x);}'
)


table(f(1e6, 1, 5))
#> 
#>      1      2      3      4      5 
#> 200115 200645 200017 199667 199556
```

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by wleoncio** [comment]
Oh, right, good point, I didn't think that far ahead. That `norm _wgt_rcpp` weight vector looks pretty essential.

**Comment by osorensen** [comment]
In principle I think we can fix this by drawing uniform random numbers on [0, 1]. Then define percentiles based on the probabilities in `norm_wgt_rcpp`, and convert the random numbers to integers based on which percentile they fall into.

For example, if we want random integers in {1,2,3} with probabilities {0.5, 0.2, 0.3}, we draw a set of uniform random numbers U, and for each element u of U, place it into one of the following bins:

- Integer=1 if u<=0.5
- Integer=2 if u<=0.5+0.2 = 0.7
- else Integer=3.

Will see if I'm able to make a short function for doing this, completely agree that this can wait until later.

**Comment by wleoncio** [comment]
Sounds proper, using something like `randi` as an intermediate step crossed my mind as well. I expect this issue to only reoccur only once again on SMC (i.e., when we implement `smc_mallows_new_users_partial` or whatever it's called), so a short wrapper function to do that would look leaner and stable. Who knows, maybe such a function might end up in Armadillo!

**Comment by wleoncio** [comment]
For the record: done with the replacements for now. The only `Rcpp::NumericVector` left is:

https://github.com/ocbe-uio/BayesMallows/blob/3efddb09ba4798a53bb4c55d4aae4ee43daaf624/src/smc_mallows_new_users_complete.cpp#L145-L148

which will be left as is until someone figures out how to pass probability weights to an `arma::rand*()` function or a more elegant solution appears.

Replacing `Rcpp::sample()` with `Rcpp::RcppArmadillo::sample()` might eliminate the need for the aforementioned Rcpp vector, but it creates a [function-definition problem](https://stackoverflow.com/questions/44060134/rcpparmadilloextensions-sample-h-linker-error-in-r-package-build-step) which requires the usage of [access functions](https://www.learncpp.com/cpp-tutorial/access-functions-and-encapsulation/) to solve (something I'm not familiar with in C++). In other words, this sounds like more work than it's worth given our time contraints, so I'll close this issue to keep the todo list clean.
